apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-app
  namespace: fluxcdtutorial
spec:
  chart:
    spec:
      chart: ./deploy/nginx-chart
  interval: 5m
  releaseName: nginx-app
  dependsOn:
    - name: database-app
