# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# metadata:
#   name: fluxcdkustomization
#   namespace: fluxcdtutorial
# resources:
# - deployment.yaml
# - service.yaml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: multi-app-chart
    releaseName: multi-app-release
    chartPath: ./deploy/nginx-chart
    version: "0.1.0"
    valuesFile: values.yaml # Specify this only if you have a values file
    namespace: default
