namespace: fluxcdtutorial

nginx:
  enabled: true
  image: nginx
  replicaCount: 2
  service:
    type: NodePort
    port: 80
    nodePort: 30080

redis:
  enabled: true
  image: redis
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379
