
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: k8snginxappsotkust
#   namespace: fluxcdtutorial
# spec:
#   interval: 30s
#   path: ./deploy/nginx-chart
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8snginxappsot


apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8snginxappsot-helmrelease
  namespace: fluxcdtutorial
spec:
  interval: 30s
  chart:
    spec:
      chart: ./deploy/nginx-chart      # Path to your Helm chart directory
      sourceRef:
        kind: GitRepository
        name: k8snginxappsot          # Name of your GitRepository resource
        namespace: flux-system
      version: "0.1.0"                 # Optional: specify chart version, or leave out for latest
  valuesFrom:
    - configMapKeyRef:
        name: nginx-values-configmap # Optional: if you're using ConfigMap for values
        key: values.yaml
  values:
    # Optional: specify override values for your Helm chart
    replicaCount: 2
    nginx:
      service:
        type: NodePort
        nodePort: 30080

