# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Release.Name }}-nginxdep
#   namespace: {{ .Values.namespace }}
#   labels:
#     name: {{ .Release.Name }}-nginx-deploy
# spec:
#   selector:
#     matchLabels:
#       app: {{ .Release.Name }}-nginxpod
#   replicas: {{ .Values.replicas }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Release.Name }}-nginxpod
#     spec:
#       containers:
#       - name: nginx
#         image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#         imagePullPolicy: {{ .Values.image.pullPolicy }}
#         ports:
#         - containerPort: 80


{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: 80
{{- end }}

